// Mohammed Moosa ST10472990
// CLDV6212 Cloud Development B
// POE Part 1 - CoffeeNChill Canteen Management System
// Program.cs

using CoffeeNChill.Functions.Interfaces;
using CoffeeNChill.Functions.Services;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var builder = FunctionsApplication.CreateBuilder(args);


// Configures the CoffeeNChill application to run using the
// ASP.NET Core integration available in the Azure Functions
// .NET isolated worker model.
//
// This configuration supports the HTTP-triggered Azure Functions
// required by the CoffeeNChill POE.
//
// Reference:
// Microsoft Learn (2026) Guide for running C# Azure Functions
// in an isolated worker process.
builder.ConfigureFunctionsWebApplication();


// Configures Application Insights telemetry for the Functions application.
//
// These lines were generated by the Azure Functions Visual Studio template
// and are retained so that application telemetry and logging remain available.
//
// Reference:
// Microsoft Learn (2026) .NET isolated worker model.
builder.Services
    .AddApplicationInsightsTelemetryWorkerService()
    .ConfigureFunctionsApplicationInsights();


// Registers the CoffeeNChill MenuItems repository with the
// .NET dependency injection container.
//
// IMenuItemRepository
//      = abstraction used by the HTTP Function layer.
//
// MenuItemRepository
//      = concrete implementation that communicates with
//        Azure Table Storage through TableClient.
//
// Dependency flow:
//
// HTTP Function
//      |
//      v
// IMenuItemRepository
//      |
//      v
// MenuItemRepository
//      |
//      v
// Azure.Data.Tables TableClient
//      |
//      v
// MenuItems Azure Table
//
// Registering the repository here allows Functions such as
// CreateMenuItem and GetAllMenuItems to request
// IMenuItemRepository through constructor injection rather
// than creating Azure storage clients themselves.
//
// The repository is registered as a singleton because it does not
// contain request-specific state and its TableClient can be reused
// across function executions.
//
// Reference:
// Microsoft Learn (2026) .NET isolated worker model -
// dependency injection and application configuration.
builder.Services.AddSingleton<IMenuItemRepository, MenuItemRepository>();


// Builds the configured Azure Functions application and starts
// the Functions worker so that it can process incoming requests.
builder.Build().Run();